CREATE TABLE categorias (
idCat number GENERATED BY DEFAULT ON NULL AS IDENTITY primary key,
nombre varchar2(50)
)

CREATE TABLE productos (
idProd number GENERATED BY DEFAULT ON NULL AS IDENTITY primary key,
nombre varchar2(20),
idCat number
)

CREATE TABLE ventas (
idVent number GENERATED BY DEFAULT ON NULL AS IDENTITY primary key,
fecha TIMESTAMP,
idProd number
)

SELECT * FROM categorias;
SELECT * FROM productos;
SELECT * FROM ventas;

ALTER TABLE productos 
ADD CONSTRAINT fk_idCat
FOREIGN KEY (idCat)
REFERENCES categorias(idCat);

ALTER TABLE ventas 
ADD CONSTRAINT fk_idProd
FOREIGN KEY (idProd)
REFERENCES productos(idProd);

INSERT INTO categorias(nombre) VALUES ('Huawei');
INSERT INTO categorias(nombre) VALUES ('Samsung');

INSERT INTO productos(nombre, idCat) VALUES ('Huawei Y 2018',1);
INSERT INTO productos(nombre, idCat) VALUES ('Samsung Y 2018',2);

INSERT INTO ventas (fecha, idProd) VALUES (SYSTIMESTAMP, 1);
INSERT INTO ventas (fecha, idProd) VALUES ('26/12/22 17:12:06', 1);
INSERT INTO ventas (fecha, idProd) VALUES ('20/08/22 13:12:06', 1);
INSERT INTO ventas (fecha, idProd) VALUES ('06/02/22 12:12:06', 1);
INSERT INTO ventas (fecha, idProd) VALUES ('30/02/21 11:12:06', 1);
INSERT INTO ventas (fecha, idProd) VALUES ('20/10/21 10:12:06', 1);
INSERT INTO ventas (fecha, idProd) VALUES (SYSTIMESTAMP, 2);
INSERT INTO ventas (fecha, idProd) VALUES ('24/12/21 08:12:06', 2);
INSERT INTO ventas (fecha, idProd) VALUES ('17/02/21 15:12:06', 2);
INSERT INTO ventas (fecha, idProd) VALUES ('09/08/22 12:12:06', 2);
INSERT INTO ventas (fecha, idProd) VALUES ('28/09/22 11:12:06', 2);


SELECT 
v.fecha,
p.nombre,
c.nombre
FROM productos p
INNER JOIN categorias c ON c.idCat = p.idCat
INNER JOIN ventas v ON v.idProd = p.idProd
WHERE rownum <= 5
ORDER BY v.fecha DESC
